In [ ]:
import numpy as np
import pandas as pd
import  seaborn as sns
from matplotlib import pyplot as plt
from scipy import stats

In [ ]:
df = pd.read_csv("my_file (1).csv")

In [ ]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [ ]:
# the artist in acd order and avg gross
df_sort = df.sort_values(['Shows', 'Artist'], ascending= [True, False])

In [ ]:

df_sort

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]

In [ ]:
df_sort

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]

In [ ]:
df[df['Shows'] > 130]
# we are flitering

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]

In [ ]:
# add a new column in our dataset
df ["New column"] = df["Shows"] > 100

In [ ]:
df.head(10)

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.,New column
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1],False
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3],False
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6],False
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7],True
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8],False
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9],False
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11],True
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12],False
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13],False
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14],False

In [ ]:
df["New column"]

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10     True
11     True
12     True
13     True
14    False
15     True
16    False
17    False
18     True
19    False
Name: New column, dtype: bool

In [ ]:
#missing data e.g.. Nan, null
# duplicates

df.isnull().sum()#checking fro missing values
df.fillna(0)# put 0 where there are missing value
df.dropna() # drop the column that missing data ."subset= " drop spec column . df.df_duplicate(subset = " artist")

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.,New column
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1],False
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3],False
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6],False
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7],True
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9],False

In [ ]:
df.drop_duplicates(subset="Artist")# removing the duplicates

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.,New column
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1],False
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3],False
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6],False
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7],True
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11],True
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18],True
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19],True
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20],True
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25],True

In [ ]:
#fill a selected column by 0
#all time peak has alot of 0
df["All Time Peak"].fillna(0)

0          2
1       7[2]
2       2[5]
3      10[7]
4          0
5      10[9]
6          0
7          0
8          0
9          0
10         0
11    14[17]
12         0
13         0
14         0
15         0
16         0
17         0
18         0
19         0
Name: All Time Peak, dtype: object

In [ ]:
#select avg.
#fill the avg value  with mean
df['Shows'].fillna(df['Shows'].mean())

0      56
1      56
2      85
3     156
4      53
5      88
6     131
7      41
8      49
9      85
10    132
11    203
12    151
13    325
14     60
15    142
16     98
17     82
18    121
19     86
Name: Shows, dtype: int64

In [ ]:
# help us to create our outlier
df.describe()

            Rank       Shows
count  20.000000   20.000000
mean   10.450000  110.000000
std     5.942488   66.507617
min     1.000000   41.000000
25%     5.750000   59.000000
50%    10.500000   87.000000
75%    15.250000  134.500000
max    20.000000  325.000000

In [ ]:
# calculate IQR
q1 = df["Shows"].quantile(0.25)
q3 = df["Shows"].quantile(0.75)
IQR = q3 - q1

In [ ]:
#define outlier boundries
lower_bound = q1 - 1.5 * IQR
upper_bound = q3 + 1.5 * IQR

In [ ]:
lower_bound

np.float64(-54.25)

In [ ]:
upper_bound

np.float64(247.75)

In [ ]:
df[df["Shows"]<= lower_bound]

Empty DataFrame
Columns: [Rank, Peak, All Time Peak, Actual gross, Actual gross(in 2022 dollars), Artist, Tour title, Year(s), Shows, Average gross, Ref., New column]
Index: []

In [ ]:
df[df["Shows"]>= upper_bound]

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.,New column
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20],True

In [ ]:
# calculatre the zscore
df['Z_score'] = np.abs(stats.zscore(df['Shows']))

In [ ]:
#identify outliers (typically Z-score > 3 is considered an outlier)
outliers = df[df['Z_score'] > 3]
print("Outliers:")
print(outliers)

Outliers:
    Rank   Peak All Time Peak  Actual gross Actual gross(in 2022 dollars)  \
13    14  1[20]           NaN  $200,000,000                  $299,676,265

   Artist                                Tour title    Year(s)  Shows  \
13   Cher  Living Proof: The Farewell Tour ‡[21][a]  2002–2005    325

   Average gross  Ref.  New column   Z_score
13      $615,385  [20]        True  3.316693

In [ ]:
df.head(10)

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.,New column,Z_score
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1],False,0.833030
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3],False,0.833030
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6],False,0.385662
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7],True,0.709618
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8],False,0.879309
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9],False,0.339383
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11],True,0.323956
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12],False,1.064427
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13],False,0.941015
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14],False,0.385662

In [ ]:
# Group by single column and calculate mean. The mean fri true and false
df.groupby('New column')['Shows'].mean()

New column
False     69.916667
True     170.125000
Name: Shows, dtype: float64

In [ ]:
df.groupby('Artist')['Shows'].mean()# how many  avg show the artist had

Artist
Adele           121.00
Beyoncé          79.00
Celine Dion     131.00
Cher            325.00
Katy Perry      151.00
Lady Gaga       150.50
Madonna          78.75
Pink            113.00
Taylor Swift     70.00
Name: Shows, dtype: float64

In [ ]:
df.groupby(['Artist','Year(s)'])['Shows'].mean()

Artist        Year(s)
Adele         2016–2017    121.0
Beyoncé       2013–2014    132.0
              2016          49.0
              2023          56.0
Celine Dion   2008–2009    131.0
Cher          2002–2005    325.0
Katy Perry    2014–2015    151.0
Lady Gaga     2009–2011    203.0
              2012–2013     98.0
Madonna       2006          60.0
              2008–2009     85.0
              2012          88.0
              2015–2016     82.0
Pink          2013–2014    142.0
              2018–2019    156.0
              2023–2024     41.0
Taylor Swift  2013–2014     86.0
              2015          85.0
              2018          53.0
              2023–2024     56.0
Name: Shows, dtype: float64

In [ ]:
print("Hello world")

Hello world